#!/bin/sh
cd src
echo "Deleted 'gamestate/dcon_generated.hpp' to not waste time formatting!"
sleep 2
rm gamestate/dcon_generated.hpp
exec find . -regex '.*\.\(cpp\|hpp\|cc\|cxx\)' -exec clang-format -style=file -i --verbose {} \;
