/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define DEBUG 1

#undef FRIBIDI_NO_DEPRECATED

#define HAVE_MEMMOVE

#define HAVE_MEMORY_H 1

#define HAVE_MEMSET

#define HAVE_STDLIB_H 1

#define HAVE_STRDUP

#define HAVE_STRINGIZE 1

#undef HAVE_STRINGS_H

#define HAVE_STRING_H 1

#undef HAVE_SYS_TIMES_H

