/* fribidi-unicode-version.h
 * generated by gen-unicode-version (fribidi unknown)
 * from the file ReadMe.txt */

#define FRIBIDI_UNICODE_VERSION "15.1.0"
#define FRIBIDI_UNICODE_MAJOR_VERSION 15
#define FRIBIDI_UNICODE_MINOR_VERSION 1
#define FRIBIDI_UNICODE_MICRO_VERSION 0

/* End of generated fribidi-unicode-version.h */
